name: notes_hive
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  path: ^1.7.0
  path_provider: ^1.6.11
  provider: ^4.1.3
  hive_flutter: ^0.3.0+2
  hive: ^1.4.1+1
  flutter_bloc: ^6.0.0
  mockito: 
  equatable: 
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  hive_generator:
  bloc_test: 


flutter:


  uses-material-design: true